from random import choice, randint
from faker import Faker
fake = Faker()

def generate_message(is_spam):
    spam_keys = ["free", "call", "text", "stop", "mobile", "reply", "win", "prize", "cash", "urgent", "claim", "guaranteed", "congratulations", "visit", "click", "credit", "offer", "unsubscribe"]
    fines = ["tolls", "toll", "fine", "penalty", "fee", "charge", "ticket", "violation", "citation", "summons", "invoice", "bill", "payment", "due", "past due", "overdue", "late", "delinquent", "unpaid", "outstanding", "balance", "collection", "debt", "owed", "pay", "payable", "settle", "settlement", "resolve", "arrears", "lien", "levy", "seizure", "confiscation", "restitution", "damages", "compensation", "reimbursement"]
    safe_keys = ["love", "come", "got", "home", "know", "like", "look", "new", "one", "see", "time", "want", "day", "good", "make", "need", "people", "think", "way", "well", "work", "year", "back", "give"]
    location = ["France", "Sydney", "Bourke", "Melbourne", "Australia", "New York", "California", "Texas", "Florida", "Alaska", "Hawaii", "Canada", "Mexico", "Brazil", "Argentina", "Chile", "Peru", "Colombia", "Venezuela", "Ecuador", "Bolivia", "Paraguay", "Uruguay", "Guyana", "Suriname", "French Guiana"]
    meals = ["lunch", "dinner", "breakfast", "brunch", "supper", "snack", "dessert", "appetizer", "entree", "main course", "side dish", "starter", "soup", "salad", "sandwich", "burger", "pizza", "pasta", "noodles", "rice", "curry", "stew", "gravy", "sauce", "dip"]
    subjects = ["security", "account", "order", "delivery", "payment", "package", "transaction", "message", "fine", "issue", "alert", "balance", "breach", "notice", "warning", "reward", "activity", "threat", "scan"]
    slang = ["hip", "lol", "lmao", "rofl", "brb", "ttyl", "omg", "tmi", "btw", "idk", "tbh", "fomo", "yolo", "fml", "smh", "imo", "imho", "irl", "nvm", "jk", "tbf", "tmi", "tbt", "hit", "hmu", "l8r", "nbd", "np", "omw", "sry", "sup", "thx", "wtf", "wyd"]
    products = ["smartphone", "vacation package", "luxury watch", "designer handbag", "gourmet coffee subscription", "home theater system", "fitness tracker", "spa treatment", "gaming console", "smart home device", "fashion accessory", "premium headphones", "meal delivery service", "beauty box", "wine club membership", "fitness class package", "book club subscription", "movie streaming service", "gourmet food hamper", "home decor item"]
    actions = ["claim your prize", "learn more", "register now", "subscribe and win", "click here and enjoy", "unlock your reward", "get your gift", "redeem your offer", "grab your deal", "discover now", "explore and save", "shop and win", "secure your discount", "enjoy your bonus", "activate your membership", "unlock your savings", "claim your reward", "get your freebie", "subscribe and save", "shop and save"]
    places = ["the park", "local cafe", "downtown bookstore", "community gym", "city museum", "beachfront restaurant", "neighborhood theater", "botanical garden", "mountain trail", "riverside picnic spot", "rooftop bar", "lakefront pier", "forest campsite", "historic landmark", "seaside promenade", "hilltop viewpoint", "urban art gallery", "farmers' market", "sports stadium", "shopping mall"]
    events = ["concert", "movie night", "dinner party", "theater show", "art exhibition", "book club meeting", "game night", "karaoke session", "birthday celebration", "housewarming party"]
    adjectives = ["important", "urgent", "final", "exclusive", "confidential", "critical", "time-sensitive", "immediate", "final reminder", "security alert"]
    store = ["apple", "facebook", "instagram", "twitter", "amazon", "ebay", "etsy", "spotify", "netflix", "hulu", "youtube", "tiktok", "snapchat", "linkedin", "pinterest", "reddit", "twitch", "discord", "whatsapp", "telegram", "signal", "zoom", "slack", "microsoft", "google", "yahoo", "bing", "duckduckgo", "firefox", "chrome", "safari", "opera", "edge", "brave", "vivaldi", "tor", "linux", "windows", "macos", "ios", "android", "blackberry", "nokia", "samsung", "lg", "sony", "htc", "huawei", "xiaomi", "oneplus", "motorola"]

    spam_templates = [
        f"Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to {fake.phone_number()} to receive entry question(std txt rate)T&C's apply {fake.url()}",
        f"{choice(fines)}! Your Mobile No {fake.phone_number()} has been awarded a £2,000 Bonus Caller Prize. Call {fake.phone_number()} from landline. Claim 3030. Valid 12hrs only.",
        f"Urgent! Please call {fake.phone_number()} from your landline. Your ABTA complimentary 4* Tenerife Holiday or £5000 cash await collection SAE T&Cs Box {fake.url()}",
        f"Congratulations! You have been selected to receive a {choice(['vacation', 'car', 'cash prize'])}. Please call {fake.phone_number()} immediately to claim your reward.",
        f"Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to {fake.phone_number()} to receive entry question(std txt rate)T&C's apply {fake.url()}",
        f"{choice(fines)}! Your Mobile No {fake.phone_number()} has been awarded a £2,000 Bonus Caller Prize. Call {fake.phone_number()} from landline. Claim 3030. Valid 12hrs only.",
        f"Urgent! Please call {fake.phone_number()} from your landline. Your ABTA complimentary 4* Tenerife Holiday or £5000 cash await collection SAE T&Cs Box {fake.url()}",
        f"Congratulations! You have been selected to receive a {choice(['vacation', 'car', 'cash prize'])}. Please call {fake.phone_number()} immediately to claim your reward.",
        f"Warning: You have won {choice(['a $1000 Walmart gift card', 'an iPhone'])}. Click {fake.url()} to claim now! Offer expires today.",
        f"You've won a luxury vacation package to {choice(location)}! Call now at {fake.phone_number()} to claim your prize.",
        f"URGENT: Your account has been selected for a security upgrade. Click {fake.url()} now to secure your account.",
        f"Congratulations! You've been chosen for a special discount at {fake.company()}! Redeem your offer now at {fake.url()}.",
        f"Limited time offer! Get a free {choice(['iPad', 'smartphone', 'laptop'])} with your next purchase. Visit {fake.url()} to claim.",
        f"Warning: Your account is at risk of suspension! Verify your information now at {fake.url()} to avoid service interruption.",
        f"Your credit score has been upgraded! Claim your new score at {fake.url()} and unlock exclusive benefits.",
        f"You've been selected for a VIP shopping experience at {fake.company()}! Call now at {fake.phone_number()} to reserve your spot.",
        f"Claim your prize now! You've won {choice(['$1000 cash', '$500 gift card', 'a luxury watch'])}. Visit {fake.url()} to collect.",
        f"Act fast! You've been pre-approved for a personal loan of up to $10,000. Apply now at {fake.url()} for instant approval.",
        f"Important: Your subscription is expiring! Renew now at {fake.url()} to continue enjoying our services."
        F"Your account has been credited with {choice(['$100', '$500', '$1000'])}. Click {fake.url()} to claim your reward.",
        f"Congratulations! You've won {choice(['a', 'an'])} {choice(products)}! {choice(actions)} at {fake.url()}! Limited time only.",
        f"Alert: {choice(subjects)} {choice(['issue', 'update', 'alert'])}. {choice(['Please verify', 'Confirm', 'Secure'])} your details immediately at {fake.url()}.",
        f"Exclusive to you! {choice(['Get', 'Claim', 'Enjoy'])} 50% off on your next {choice(['purchase', 'booking', 'order'])}. Visit {fake.url()} before this {choice(['offer expires', 'deal ends'])}!",
        f"Security Notice: Suspicious activity detected. Urgently confirm your credentials at {fake.url()} to prevent {choice(['fraud', 'unauthorized access'])}.",
        f"Missed connection: We noticed you left something in your cart. Return to {fake.url()} to complete your purchase and enjoy an additional {randint(5, 20)}% off!",
        f"Your {choice(['order', 'package', 'delivery'])} is on its way! Track your {choice(['shipment', 'parcel', 'consignment'])} at {fake.url()} for real-time updates.",
        f"Hey {fake.name()} just wanted to share this {choice(adjectives)} article I read. Check it out when you have time: {fake.url()}.",
        f"Final Warning: Unclaimed reward of {choice(['a $500 gift card', 'an exclusive discount'])}. Act now by visiting {fake.url()} before {choice(['it expires tonight', 'the offer ends'])}!",
        f"Notice: Your subscription to {choice(['our service', 'premium access'])} is about to expire. Renew now at {fake.url()} to avoid interruption.",
        f"{choice(['Limited Time Offer', 'Last Chance'])}: Your chance to win {choice(['a new car', 'a year of free groceries'])} ends soon. Enter now at {fake.url()}!",
        f"Quick Action Required: Confirm your email to continue receiving {choice(['amazing deals', 'important notifications'])} from us. Confirm at {fake.url()}.",
        f"Exclusive Invitation: You’ve been selected to participate in our {choice(['beta test', 'survey'])}. Complete it and win {choice(['a $50 voucher', 'a special prize'])} at {fake.url()}.",
        f"Warning: {choice(['Your account is at risk', 'Suspicious login attempts detected'])}. Secure your account immediately by visiting {fake.url()}.",
        f"Your opinion counts! Take our quick survey and you could win {choice(['a trip to Hawaii', 'a brand new iPhone'])}. Start now at {fake.url()}.",
        f"Earn Money from Home: Start making up to ${randint(100, 500)} a day! Learn how by clicking this link: {fake.url()}.",
        f"Package Alert: A parcel is waiting for you. Claim it by confirming your shipping details at {fake.url()}.",
        f"You're a Winner! Your entry was selected. To receive your {choice(['luxury watch', 'high-tech gadget'])}, visit {fake.url()} immediately.",
        f"Hi {fake.name()} you've won {choice(products)}! Click here to {choice(actions)} and claim your prize: {fake.url()}.",
        f"{choice(adjectives)} reminder: Your appointment is scheduled for {fake.time()} on {fake.date()} at {choice(places)}.",
        f"Hey {fake.name()} just a {choice(adjectives)} message: Your {choice(subjects)} requires immediate attention. Please check it now.",
        f"Urgent message for {fake.name()}: Your {choice(subjects)} needs verification. Click here to resolve the issue: {fake.url()}.",
        f"{choice(spam_keys)} {fake.name()}! Let's catch up at {choice(events)} this {fake.date()} at {fake.time()}.",
        f"Attention {fake.name()}! Your {choice(subjects)} is pending. Complete the action now to avoid penalties.",
        f"Final reminder for {fake.name()}: Your {choice(products)} order is ready for delivery. Confirm the details here: {fake.url()}.",
        f"Hi {fake.name()} we've noticed unusual {choice(subjects)} activity. Please review and take action immediately.",
        f"{fake.name()} you're invited to an exclusive event: {choice(events)} this {fake.date()} at {choice(places)}. Don't miss out!",
        f"Greetings {fake.name()} your {choice(products)} subscription expires soon. Renew now at {fake.url()} and enjoy uninterrupted service.",
        f"Attention: Unpaid {choice(['tolls', 'fees', 'fines'])} detected. Pay now to avoid legal action. Visit {fake.url()} for payment options.",
        f"Important Notice: Your {choice(['toll', 'fee', 'fine'])} payment is overdue. Pay immediately at {fake.url()} to avoid penalties.",
        f"Final Reminder: Unpaid {choice(['tolls', 'fees', 'fines'])} of ${randint(50, 200)} are pending. Clear your dues now at {fake.url()}.",
        f"Urgent Action Required: Pay your {choice(['tolls', 'fees', 'fines'])} of ${randint(100, 500)} immediately to avoid legal consequences. Visit {fake.url()}.",
        f"Payment Alert: Your {choice(['toll', 'fee', 'fine'])} of ${randint(20, 100)} is due. Pay now at {fake.url()} to prevent further action.",
        f"{choice(subjects)}: act now {fake.url()} to {choice(actions)}!",
        f"{choice(subjects)}: act now {fake.url()} to {choice(actions)}!",
        f"{choice(subjects)}: act now {fake.url()} to {choice(actions)}!",
        f"TOLL NOTICE: act now {fake.url()} or face jail time of {randint(1, 5)} years",
        f"TOLL NOTICE: act now or you'll be fined ${randint(50, 200)} {fake.url()} or face jail time",
        f"FINAL NOTICE: act now {fake.url()} to avoid jail time",
        f"Your apple ID has been locked. Click {fake.url()} to unlock",
        f"Your {choice(store)} has been locked. Click {fake.url()} to unlock",
        f"You've won a free {choice(products)}! Click {fake.url()} to claim",
        f"You've won a free {choice(store)} voucher valued ${randint(500, 2000)}! Click {fake.url()} to claim",
        f"Final alert from {choice(store)}: Your account has been locked. Click {fake.url()} to unlock",
        f"{choice(subjects)}: act now {fake.url()} to {choice(actions)}!",
        f"{choice(subjects)}: act now {fake.url()} to {choice(actions)}!",
        f"{choice(subjects)}: act now {fake.url()} to {choice(actions)}!",
        f"TOLL NOTICE: act now {fake.url()} or face jail time of {randint(1, 5)} years",
        f"TOLL NOTICE: act now or you'll be fined ${randint(50, 200)} {fake.url()} or face jail time",
        f"FINAL NOTICE: act now {fake.url()} to avoid jail time",
        f"Your apple ID has been locked. Click {fake.url()} to unlock",
        f"Your {choice(store)} has been locked. Click {fake.url()} to unlock",
        f"You've won a free {choice(products)}! Click {fake.url()} to claim",
        f"You've won a free {choice(store)} voucher valued ${randint(500, 2000)}! Click {fake.url()} to claim",
        f"Final alert from {choice(store)}: Your account has been locked. Click {fake.url()} to unlock",
    ]
    ham_templates = [
        f"Hey I'm at {choice(location)} right now. I'll be home in 30 minutes. See you soon!",
        f"Hi I'm running late. I'll be home in 1 hour. Can you please start {choice(meals)}? Thanks!",
        f"Good morning! Just wanted to say I love you. How did you sleep?",
        f"Can you believe we've been friends for so long? Remember that time in {choice(location)}? Those were the days!",
        f"Hey are you free this weekend? Thinking about going to {choice(['the beach', 'a movie', 'a new restaurant'])}. Let me know!",
        f"Just finished reading the book you recommended. Absolutely loved it! Let's talk about it when you have time.",
        f"Can't wait for our dinner at {choice(['the new Italian place', 'that sushi bar'])} tonight. It’s been too long!",
        f"Reminder: Your doctor’s appointment is on {fake.date_this_month()}. Don’t forget to confirm!",
        f"Mom called. She wants us to visit this weekend. Should I tell her we'll go?",
        f"Are we still on for the hike tomorrow? Heard it might rain. Maybe bring a raincoat just in case.",
        f"Work has been so hectic lately! Could use a day off. How about a road trip next weekend?",
        f"Managed to fix that leaky faucet finally. It was about time. I might tackle the garage next.",
        f"Have you seen the latest episode of {choice(['Stranger Things', 'Game of Thrones'])}? No spoilers please planning to watch tonight!",
        f"Can you pick up some {choice(['milk', 'eggs', 'bread', 'coffee'])} on your way home? We're running low.",
        f"Remember to water the plants today. They're looking a bit dry.",
        f"Just finished reading {choice(['a novel', 'a mystery book', 'a biography'])}. Absolutely loved it! We should talk about it over coffee.",
        f"Can't wait for our dinner at {choice(['the new Italian place', 'that sushi bar', 'the downtown grill'])} tonight. It’s been too long!",
        f"Reminder: Your doctor’s appointment is on {fake.date_this_month()}. Don’t forget to confirm!",
        f"Mom called. She wants us to visit this weekend for {choice(['her birthday', 'a family reunion', 'a barbecue'])}. Should I tell her we'll go?",
        f"Are we still on for the hike tomorrow? Heard it might rain. Maybe bring {choice(['a raincoat', 'an umbrella'])} just in case.",
        f"Work has been so hectic lately! Could use a day off. How about a road trip to {choice(['the mountains', 'the lake', 'the coast'])} next weekend?",
        f"Managed to fix that leaky faucet finally. It was about time. Next project: {choice(['the garage', 'the garden shed', 'the attic'])}.",
        f"Have you seen the latest episode of {choice(['Stranger Things', 'Game of Thrones', 'The Witcher'])}? No spoilers please planning to watch tonight!",
        f"Happy Birthday! Hope you have a fantastic day filled with all your favorite things like {choice(['cake', 'ice cream', 'pizza'])}. Let’s celebrate soon!",
        f"Been thinking about getting a new car. Any recommendations? Something {choice(['fuel-efficient', 'electric', 'hybrid'])} but still fun to drive.",
        f"Quick question: Do you have the recipe for grandma’s famous {choice(['pie', 'lasagna', 'roast chicken'])}? Want to try making it this weekend.",
        f"Saw a great deal on flights to {choice(['Japan', 'Italy', 'Iceland'])} for next spring. Should we consider it? Always wanted to see the {choice(['cherry blossoms', 'Colosseum', 'Northern Lights'])}.",
        f"Hope the kids are doing well. Let’s set up a playdate soon. Maybe next {choice(['Saturday', 'Sunday', 'weekend'])}?",
        f"Thinking about starting a blog about my {choice(['gardening', 'cooking', 'travel'])} adventures. Any tips on how to get started?",
        f"Hey just a heads up I left my {choice(['jacket', 'book', 'sunglasses'])} at your place last time. Mind if I swing by to pick it up?",
        f"Hope you’re doing well. Just checking in since it’s been a while since our last {choice(['chat', 'meet-up', 'call'])}.",
        f"Found an old photo of us from high school at {choice(['prom', 'graduation', 'the football game'])}! We look so different. Time really flies.",
        f"Can you pick up some {choice(['milk', 'eggs', 'bread', 'coffee'])} on your way home? We're running low.", 
        f"I just got a {choice(fines)} for speeding. Can you believe it? I was only going 5 miles over the limit!",
        f"Check this {fake.url()} out! It's a new recipe I found for {choice(meals)}. I'm thinking of trying it out this weekend.",
        f"{fake.text()}",
        f"{fake.text()}",
        f"hey bestie how's it going? I'm thinking of going to {choice(['the beach', 'the park', 'the mall'])} this weekend. Wanna join?",
        f"Hey I'm at {choice(location)} right now. I'll be home in 30 minutes. See you soon!",
        f"can you believe it? I just won {choice(['a trip', 'a car', 'a house'])} in a contest! I'm so excited!",
        f"just wanted to say I love you. How did you sleep?",
        f"heeeeey",
        f"what's up?",
        f"how are you? {fake.name()}",
        f"Hey {fake.name()} how's it going?",
        f"I'm so so done with this day can you believe {fake.name()} did this?",
        f"Did you get this message? I'm not sure if it went through.",
        f"I just discovered a new hobby: {choice(['knitting', 'skydiving', 'juggling flaming torches'])}. Want to join me?",
        f"Guess what? I found a secret stash of {choice(['chocolate', 'treasure', 'old coins'])} in the backyard!",
        f"Hey, do you remember our failed attempt at {choice(['skydiving', 'cooking sushi', 'building a rocket'])}? We should try it again!",
        f"Currently obsessed with {choice(['astrology', 'quantum physics', 'ancient history'])}. Want to nerd out with me?",
        f"Can't stop listening to {choice(['classical music', '90s hip-hop', 'Mongolian throat singing'])}. It's strangely addictive!",
        f"Just adopted a pet {choice(['ferret', 'alpaca', 'parrot'])}. Any tips on taking care of it?",
        f"Accidentally locked myself out of the house again. Can you bring the spare key?",
        f"Found a time capsule from 1995 buried in the backyard. The contents are hilarious!",
        f"Thinking of redecorating the living room with a {choice(['space theme', 'vintage vibe', 'tropical paradise'])}. What do you think?",
        f"Managed to solve a Rubik's Cube in under a minute! Feeling like a genius right now.",
        f"Just had the weirdest dream about {choice(['flying pigs', 'talking vegetables', 'unicorns playing poker'])}. Interpretations welcome!",
        f"Started learning {choice(['Japanese', 'Swahili', 'Klingon'])}. It's harder than I thought!",
        f"Accidentally dyed my hair {choice(['bright green', 'bubblegum pink', 'electric blue'])}. Not sure if I love it or hate it.",
        f"Planning a spontaneous trip to {choice(['the moon', 'the Amazon rainforest', 'Antarctica'])}. Care to join?",
        f"Can't decide what to have for dinner. Should I go with {choice(['tacos', 'sushi', 'macaroni and cheese'])} or something else?",
        f"Just watched a documentary about {choice(['bigfoot sightings', 'alien abductions', 'time travel theories'])}. Mind officially blown!",
        f"Started a collection of {choice(['vintage stamps', 'funky socks', 'antique teapots'])}. It's becoming an obsession.",
        f"Accidentally sent an embarrassing text to my boss instead of my friend. Can't face them at work tomorrow!",
        f"Thinking of starting a band. I'll play the {choice(['keytar', 'accordion', 'cowbell'])}. Want to join?",
        f"Spent the entire day binge-watching {choice(['reality TV shows', 'documentaries about penguins', '90s sitcoms'])}. Productivity level: zero.",
        f"Just invented a new dance move called the {choice(['funky chicken', 'moonwalk shuffle', 'robotic salsa'])}. It's going to be a viral sensation!",
        f"Lost my favorite {choice(['lucky socks', 'magic wand', 'invisible cloak'])}. How am I supposed to function without it?",
        f"Found a portal to another dimension in the basement. Should I explore it or call the authorities?",
        f"Accidentally signed up for a {choice(['marathon', 'hotdog eating contest', 'karaoke competition'])}. Not sure how I feel about it.",
        f"Just spotted a UFO in the sky! Either that or it's a really shiny balloon.",
        f"Started a new skincare routine involving {choice(['snail slime', 'bee venom', 'unicorn tears'])}. Hope it works!",
        f"Accidentally booked a one-way ticket to {choice(['Mars', 'Narnia', 'Atlantis'])}. Anyone want to join me on this adventure?",
        f"Decided to become a {choice(['beekeeper', 'sword swallower', 'professional yo-yoer'])}. It's time for a career change!",
        f"Found a secret door behind the bookshelf. Wonder what mysteries it holds?",
        f"Got invited to a {choice(['medieval banquet', 'zombie apocalypse survival workshop', 'circus training camp'])}. Should I go?",
        f"Accidentally joined a cult. They seem nice, but I'm starting to have second thoughts.",
        f"Got a tattoo of a {choice(['unicorn', 'sushi roll', 'Eiffel Tower'])} on a whim. Regret level: TBD.",
        f"Started talking to plants to help them grow faster. Surprisingly, it seems to be working!",
        f"Accidentally invented a new language while sleep-talking. Still trying to decipher what I said.",
        f"Decided to become a professional {choice(['pirate', 'astronaut', 'fortune teller'])}. Career counselor was not amused.",
        f"Found a secret underground bunker in the backyard. Should I be concerned?",
        f"Accidentally booked a room in a haunted hotel. Hope the ghosts are friendly!",
        f"Started a petition to make {choice(['national penguin awareness day', 'international pancake day', 'global UFO day'])} a public holiday. Who's with me?",
        f"Decided to live off the grid and become a {choice(['hermit', 'beekeeper', 'mountain goat herder'])}. Farewell, civilization!",
        f"Accidentally enrolled in a ninja training course. It's harder than it looks in the movies!",
        f"Found a genie lamp in the attic. Wish suggestions welcome!",
        f"Decided to become a professional {choice(['unicorn trainer', 'chocolate taster', 'cloud sculptor'])}. Dream job, here I come!",
        f"Accidentally started a flash mob in the grocery store. Now everyone's dancing in the produce aisle.",
        f"Joined a secret society of {choice(['cat lovers', 'avocado enthusiasts', 'sock puppet aficionados'])}. Membership benefits include unlimited snacks.",
        f"Accidentally ordered 100 pounds of {choice(['bubble wrap', 'gummy bears', 'feathers'])} online. Anyone need some?",
        f"Started a rumor that I'm secretly a {choice(['time traveler', 'vampire', 'alien from Mars'])}. Let's see how long it takes to spread.",
        f"Accidentally wandered into a parallel universe where everything is {choice(['pink', 'upside down', 'made of cheese'])}. Still trying to find my way back.",
        f"Decided to become a professional {choice(['fortune cookie writer', 'cloud watcher', 'banana peel artist'])}. It's a niche market, but I'm determined.",
        f"Accidentally got invited to a {choice(['pirate-themed wedding', 'clown convention', 'mime workshop'])}. Not sure if I should RSVP.",
        f"Started a conspiracy theory that {choice(['pigeons are government spies', 'the moon is made of cheese', 'cats control the weather'])}. It's gaining traction.",
        f"Accidentally invented a new sport involving {choice(['synchronized swimming with goldfish', 'extreme knitting', 'competitive napping'])}. It's going to be the next big thing.",
        f"Decided to become a professional {choice(['taco critic', 'professional cuddler', 'banana peel slip tester'])}. My resume is going to be interesting.",
        f"Accidentally stumbled upon a secret society of {choice(['penguin whisperers', 'unicorn trainers', 'ghost hunters'])}. Should I join?",
        f"Started a rumor that I'm secretly a {choice(['wizard', 'mermaid', 'time traveler'])}. Let's see how long it takes to reach Hogwarts.",
        f"Accidentally enrolled in a magic school. Turns out, I'm not very good at spells.",
        f"Decided to become a professional {choice(['space tourist', 'professional napper', 'sushi chef'])}. Career options are limitless!",
        f"Accidentally started a flash mob in the library. Turns out, librarians love to dance!",
        f"Joined a secret society of {choice(['penguin enthusiasts', 'unicorn lovers', 'banana aficionados'])}. Membership perks include free snacks.",
        f"Accidentally ordered 100 pounds of {choice(['bubble wrap', 'gummy bears', 'feathers'])} online. Anyone need some?",
        f"Started a rumor that I'm secretly a {choice(['time traveler', 'vampire', 'alien from Mars'])}. Let's see how long it takes to spread.",
        f"Accidentally wandered into a parallel universe where everything is {choice(['pink', 'upside down', 'made of cheese'])}. Still trying to find my way back.",
        f"Decided to become a professional {choice(['fortune cookie writer', 'cloud watcher', 'banana peel artist'])}. It's a niche market, but I'm determined.",
        f"Accidentally got invited to a {choice(['pirate-themed wedding', 'clown convention', 'mime workshop'])}. Not sure if I should RSVP.",
        f"Started a conspiracy theory that {choice(['pigeons are government spies', 'the moon is made of cheese', 'cats control the weather'])}. It's gaining traction.",
        f"Accidentally invented a new sport involving {choice(['synchronized swimming with goldfish', 'extreme knitting', 'competitive napping'])}. It's going to be the next big thing.",
        f"Decided to become a professional {choice(['taco critic', 'professional cuddler', 'banana peel slip tester'])}. My resume is going to be interesting.",
        f"Accidentally stumbled upon a secret society of {choice(['penguin whisperers', 'unicorn trainers', 'ghost hunters'])}. Should I join?",
        f"Started a rumor that I'm secretly a {choice(['wizard', 'mermaid', 'time traveler'])}. Let's see how long it takes to reach Hogwarts.",
        f"Accidentally enrolled in a magic school. Turns out, I'm not very good at spells.",
        f"Decided to become a professional {choice(['space tourist', 'professional napper', 'sushi chef'])}. Career options are limitless!",
        f"Accidentally started a flash mob in the library. Turns out, librarians love to dance!"
    ]
    
    if is_spam:
        return choice(spam_templates)
    else:
        return choice(ham_templates)